### ISSUE TITLE
No CAT_fid_stats32.npz

### ISSUE THREAD

**Issue by Ahalang** [AlexiaJM/relativistic-f-divergences#3]
Hello， can you tell me how to find the CAT_fid_stats32.npz? Thank you.

**Comment by AlexiaJM** [comment]
See: https://github.com/AlexiaJM/relativistic-f-divergences/blob/master/setting_up_script.sh.

You can create it yourself with the command or download it from the website. For CIFAR-10 it doesn't really matter, both will be the same, but for other datasets, I recommend you create them with the commands since you want the preprocessing to be reflected in the .npz.
