### ISSUE TITLE
which command in experiments give best FID?

### ISSUE THREAD

**Issue by TranThanh96** [AlexiaJM/relativistic-f-divergences#7]
in experiments.sh file, which command should I use to get the best FID?

**Comment by AlexiaJM** [comment]
> bash fid_script.sh 10 "Stable 1 - CAT - RaSGAN      lr=.0002 D_iters=1 batch=32 betas=(.50, .999) spectral seed 1" 10000 "/home/alexia/fid_stats/CAT_fid_stats32.npz"

Commands like this one put the FID at 10k, 20k, ..., 100k iterations in a txt file (since images are generated at every 10k iterations and the script takes argument 10 to say 10*10k=100k). The best FID is generally at 100k. You can run longer for potentially even better results.


If you mean best results, RaLSGAN (--loss_D 12) or RaHingeGAN (--loss_D 13) with --arch 1 and --spectral True will get you best 32x32 results and arch 0 (potentially with --spectral True but I haven't tried) will get you good results for bigger images.

**Comment by TranThanh96** [comment]
thank you so much. I am trying to apply this method to another dataset.
